<h1>Index Action</h1>

<a href="<?php echo $this->url('album_tdg/default', array('controller' => 'album_tdg', 'action' => 'create')); ?>">Add new album</a>
<table class="table">
	<tr>
		<th>Id</th>
		<th>Artist</th>
		<th>Title</th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach($rowset as $row) : ?>
	<tr>
		<td><?php echo $row['id']; ?></td>
		<td><?php echo $row['artist']; ?></td>
		<td><?php echo $row['title']; ?></td>
		<td>
			<a href="
			<?php echo $this->url('album_tdg/default', array('controller' => 'album_tdg', 'action' => 'update', 'id' => $row['id'])); ?>">
			Edit
			</a>
		</td>
		<td>
			<a href="
			<?php echo $this->url('album_tdg/default', array('controller' => 'album_tdg', 'action' => 'delete', 'id' => $row['id'])); ?>" 
			onclick="return confirm('Are you sure you want to delete this album?')" >Delete
			</a>
		</td>
	</tr>
	<?php endforeach; ?>
</table>