-- phpMyAdmin SQL Dump
-- version 3.5.1
-- http://www.phpmyadmin.net
--
-- Хост: localhost
-- Време на генериране: 
-- Версия на сървъра: 5.5.24-log
-- Версия на PHP: 5.4.3

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- БД: `articles`
--

-- --------------------------------------------------------

--
-- Структура на таблица `article`
--

CREATE TABLE IF NOT EXISTS `article` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(145) NOT NULL,
  `body` varchar(2000) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=9 ;

--
-- Ссхема на данните от таблица `article`
--

INSERT INTO `article` (`id`, `title`, `body`) VALUES
(1, 'Gathering storm in europe', 'ACCORDING to satellite pictures and military intelligence, some 50,000 Russian troops are massed along the border with Ukraine. The forces represent a substantial fraction of Russiaâ€™s 270,000-strong army, and they cannot indefinitely maintain the high state of readiness they have been in since early March, not least because it is now the time of year when conscripts at the end of their term have to be sent home, and new ones trained.\r\n\r\nUkraineâ€™s armed forces are, by comparison, small, ill-equipped and out of position. Ukraine has just 77,000 troops. The interior ministryâ€™s paramilitary forces are of similar number, but in the south and east of the country their loyalty may be questionable. A reserve of 1m men might theoretically be mobilisedâ€”all those who are within five years of completing their military serviceâ€”but it would probably be poorly disciplined, and of very limited use.'),
(2, '2.5bn pounds loss', 'The Co-operative Group has announced losses of 2.5bn pounds for 2013, marking the worst results in the group''s 150-year history.The group said most of the losses stemmed from the Co-operative Bank, which amounted to 2.1bn pounds.That included a trading loss of 1.44bn pounds for the year to December, when the group lost control of Co-op Bank to US hedge funds.Chief executive Richard Pennycook said 2013 had been a "disastrous" year.He added: "These results should serve as a wake-up call to anyone who doubts just how serious the challenges we face are. "The scale of this disaster will rightly shock our members, our customers and our colleagues,"He also criticised the lack of transparency within the bank, which he said he believed had failed to communicate effectively with the group board."As a former public company finance director, I would not have been comfortable running with debt levels the bank was running with. So I do think there has been a lack of transparency," he said.The Co-op Group chief executive told the BBC''s business editor, Kamal Ahmed: "What we have found is a period of poor performance from management. The last five years in our proud 150-year history have been very difficult. It was not just an accident at the bank."'),
(3, 'East Ukraine militants snub Geneva deal on crisis', 'Pro-Russian separatists in Donetsk say they will not leave the government building there, defying the Kiev authorities and threatening a new international deal on Ukraine.\r\n\r\nThe separatists'' spokesman told the BBC that the Kiev government was "illegal", so they would not go until the Kiev government stepped down.\r\n\r\nRussia, Ukraine, the EU and US earlier agreed that illegal military groups in Ukraine must leave official buildings.\r\n\r\nThey reached the deal in Geneva.\r\n\r\nAlexander Gnezdilov, spokesman for the self-proclaimed Donetsk People''s Republic, said his group would evacuate the government building in the eastern city only when the "illegal" Kiev government vacated parliament and the presidential administration. \r\n\r\nThe BBC''s James Reynolds recorded his day as he and a BBC team covered events in eastern Ukraine\r\n\r\nA tense standoff continues in eastern Ukraine, where pro-Russian separatists - many of them armed - are occupying official buildings in at least nine cities and towns.\r\n\r\nAnother protest leader in Donetsk said the separatists would not leave unless pro-European demonstrators in Kiev''s Maidan Square packed up their camp first.'),
(4, 'Royal couple visit Easter agricultural show in Sydney ', 'The Duke and Duchess of Cambridge have spent their third day in Australia at the famed Sydney Royal Easter Show.\r\n\r\nThe couple, during the second leg of their trip Down Under, toured elaborate displays of produce grouped by Australian regions.\r\n\r\nThey were also greeted by a well-mannered ram named Fred, who bowed to them on one knee as they went to watch a sheep-shearing display.\r\n\r\nWilliam and Kate arrived in Australia on Wednesday having toured New Zealand.\r\n\r\nThey arrived with Prince George in tow, but the eight-month-old did not attend the agricultural show.\r\n\r\nHis parents are expected to bring him to Taronga zoo in Sydney on Sunday where an enclosure housing bilbys - a rabbit-like marsupial - will be named after him.\r\n\r\nBowing ram\r\n\r\nAt the event on Friday, the duchess, wearing a white Zimmermann dress, joked that William could use a tuft of alpaca wool to cover his bald patch.\r\n\r\nExhibitor Lyn Crejan showed the pair the wool as she talked them through a display of fruit and vegetables.'),
(5, 'Sacked doctor "was unfairly dismissed", tribunal rules', 'A heart specialist was unfairly sacked after raising concerns about patient safety, a tribunal has ruled.\r\n\r\nDr Raj Mattu was dismissed by University Hospital of Coventry and Warwickshire NHS Trust in 2010.\r\n\r\nIn 2001, he exposed the cases of two patients who died in crowded bays at Walsgrave Hospital in Coventry.\r\n\r\nThe judge ruled Dr Mattu "did not cause or contribute to his dismissal". Dr Mattu said he was "relieved" at the ruling. The trust did not comment.\r\n''Devastating'' effects\r\n\r\nEmployment Judge Pauline Hughes dismissed Dr Mattu''s claims of racial discrimination.\r\n\r\nHowever, she ruled the consultant was subject to "many detriments" by the trust as a consequence of being a whistle-blower.\r\n\r\nShe said the cardiologist''s allegations were "serious" and had "attracted a great deal of media coverage and public interest".\r\n\r\nShe also ruled that the surgeon had been treated "unfavourably" by the trust as a result of a disability.\r\n\r\nDuring the tribunal, Dr Mattu said his concerns about overcrowding on wards were ignored.\r\n\r\nHe claimed a policy of allocating five patients to four-bed bays in December 1999 prevented vital equipment being used to save the life of a 35-year-old man.'),
(6, 'South Korea ferry: Third officer "had helm"', 'The third officer was at the helm of the ferry that capsized off South Korea, investigators said, as divers worked to access the sunken hull.\r\n\r\nA total of 268 people - including scores of high school students - remain missing after Wednesday''s disaster.\r\n\r\nTwenty-eight people are now known to have died and 179 were rescued.\r\n\r\nIt is not clear why the ferry sank, but experts have suggested it either hit a rock or turned sharply, unbalancing the vessel as cargo shifted.\r\n\r\nThe vessel - named Sewol - had been travelling from Incheon, in the north-west, to the southern resort island of Jeju. It capsized and sank within a period of two hours, officials said. \r\nThe BBC''s Martin Patience, who is at the scene, says there are conflicting reports over whether divers have managed to enter the ferry.\r\n\r\nHe says one government agency reported a team of divers accessing the bridge and restaurant of the stricken vessel but that many of the students were thought to have been trapped on a different floor.\r\n\r\nBut coast guard officials quoted by Reuters later denied that divers had been deployed inside the ferry.\r\n\r\nAir was also now being injected into the ship, two reports said, both to help any people trapped inside - though officials have said that survivors are unlikely - and to help refloat the vessel.\r\n\r\nCoast guard officials, quoted by AFP, say the bodies picked up were found floating in the water, and none had been retrieved from the ship itself.\r\n\r\nThree salvage cranes have also arrived at the scene, to raise the ship or move it to another area with weaker currents.\r\n\r\nOur correspondent at the scene described "an absolutely desperate development for the families" as three more bodies were brought in from the rescue site on Friday.'),
(7, 'Labour hires Obama ''campaign chief'' David Axelrod', 'The Labour Party has appointed US election strategist David Axelrod as a strategic adviser on leader Ed Miliband''s 2015 election campaign.\r\n\r\nMr Axelrod was a key architect of Barack Obama''s victory over John McCain in the 2008 presidential race.\r\n\r\nHe will work alongside shadow foreign secretary, Douglas Alexander, who is to run Labour''s general election strategy.\r\n\r\nLabour will also call on Mr Axelrod''s consulting, firm AKVD, in its bid to win power, BBC Newsnight revealed.\r\n\r\nAfter masterminding Mr Obama''s election to the White House, Mr Axelrod went on to become a senior adviser to the president. \r\n\r\nHe quit the post in 2011 in order to work on the successful 2012 campaign to re-elect Mr Obama.\r\n\r\nThe strategist has since acted as a media commentator and as a director of the Institute of Politics at the University of Chicago.\r\n\r\n''Huge asset''\r\n\r\nEd Miliband hailed the appointment as "excellent news" and predicted the strategist would be a "huge asset to our campaign as we work to show the British people how we can change our country for the better".\r\n\r\nMr Axelrod said he had been struck by the power of the Labour leader''s ideas and the "strength of his vision".\r\n\r\nHe drew a comparison between Mr Miliband''s economic policies and the arguments articulated by Mr Obama in 2008, saying both have at their core "the experience of everyday people".\r\n\r\nHe said: "I think candidates who can win are candidates who articulate a vision that speaks to the lives and concerns of the people they are running to represent. '),
(8, 'Lewis Hamilton top in China practice ahead of Fernando Alonso', 'Lewis Hamilton beat Ferrari''s Fernando Alonso as the Mercedes driver set the pace in practice at the Chinese GP.\r\n\r\nHamilton recovered from a suspension issue that cut short his first session to beat Alonso by 0.141 seconds.\r\n\r\nMercedes driver Nico Rosberg was third, 0.411secs behind Hamilton.\r\n\r\nThe Red Bulls of Daniel Ricciardo and Sebastian Vettel were next, ahead of Williams'' Felipe Massa, Ferrari''s Kimi Raikkonen, McLaren''s Jenson Button, and the Lotus of Romain Grosjean. \r\n\r\nToro Rosso''s Daniil Kvyat was 10th, from Force India''s Nico Hulkenberg and Kevin Magnussen''s McLaren.\r\n\r\nHamilton''s fastest time came despite his complaining about understeer - a lack of front grip - when he finally made it out on to the track about 20 minutes into the second session.\r\n\r\nThe Englishman also missed about the same amount of time at the end of the first session as Mercedes decided to ensure they had enough time to fix the car. \r\n\r\nFerrari had a mixed day under the gaze for the first time of their new team principal Marco Mattiacci, who created a bit of a stir by wearing sunglasses all day despite the generally overcast weather. ');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
